name: Java pipeline
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: collecting the source code from github
        uses: actions/checkout@v4

      - name: installing java
        uses: actions/setup-java@v5.5.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: compile the java source code
        run: javac Test1.java

      - name: executing java project
        run: java Test
          
        
