name: Java application
on:
  schedule:
    - cron: "*/2 * * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning github repository
        uses: actions/checkout@v7.0.0

      - name: Install java application
        uses: actions/setup-java@v5.5.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile java project
        run: javac Test.java

      - name: Execute java project
        run: java Test
          
        
