name: Java application
on:
  push:
    
jobs:
  build:
    strategy:
      matrix:
        environment: [ "beta","gamma","delta" ]
        os: [ 17,21 ]
    runs-on: ubuntu-latest

    steps:
      - name: Cloning github repository
        uses: actions/checkout@v7.0.0

      - name: Install java application
        uses: actions/setup-java@v5.5.0
        with:
          java-version: ${{ matrix.os }}
          distribution: 'temurin'

      - name: Compile java project
        run: javac Test.java

      - name: Environment
        run: echo "${{ matrix.environment }}"

      - name: Execute java project
        run: java Test

      - name: Java version
        run: java --version

 
        
