name: Matrix Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        version: [17, 21]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Cloning GitHub repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.version }}
          distribution: temurin

      - name: Compile Java project
        run: javac Test.java

      - name: Environment
        run: echo "${{ matrix.os }}"

      - name: Execute Java project
        run: java Test

      - name: Java version
        run: java --version
