name: Demonstrating secrets and variables
on:
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Application Name
        run: echo "${{ vars.APP_NAME }}"

      - name: App password
        run: echo "${{ secrets.APP_PASSWORD }}"
